name: isar_key_value
description: A super fast key value store built on top of the isar database.
version: 0.1.1
repository: https://github.com/MohiuddinM/isar_key_value

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.0.0
  isar_generator: ^3.0.0
  build_runner: ^2.0.0
